### ISSUE TITLE
关于记录分数

### ISSUE THREAD

**Issue by nosexynomoney** [sjx233/luogu-api-docs#12]
我想获取记录分数，但是返回的json中subtasks为空,也没有score
"detail"键的值都是这样的

                      "detail": {
				"compileResult": null,
				"judgeResult": {
					"subtasks": [],
					"finishedCaseCount": 0,
					"__CLASS_NAME": "Luogu\\DataClass\\Record\\JudgeResult\\JudgeResult"
				},
				"__CLASS_NAME": "Luogu\\DataClass\\Record\\RecordDetail"
			},
没有任何评测信息

**Comment by sjx233** [comment]
可以提供记录 id 吗？

**Comment by nosexynomoney** [comment]
记录id 59249985
返回json:

{
	"code": 200,
	"currentTemplate": "RecordShow",
	"currentData": {
		"record": {
			"detail": {
				"compileResult": null,
				"judgeResult": {
					"subtasks": [],
					"finishedCaseCount": 0,
					"__CLASS_NAME": "Luogu\\DataClass\\Record\\JudgeResult\\JudgeResult"
				},
				"__CLASS_NAME": "Luogu\\DataClass\\Record\\RecordDetail"
			},
			"sourceCode": "#include<iostream>\nusing namespace std;\nint main(){\n    int a,b;\n    cin>>a>>b;\n   cout<<a+b;\n    return  0;\n}",
			"time": 0,
			"memory": 0,
			"problem": {
				"pid": "P1001",
				"title": "A+B Problem",
				"difficulty": 1,
				"fullScore": 100,
				"type": "P"
			},
			"contest": null,
			"sourceCodeLength": 111,
			"submitTime": 1633450134,
			"language": 11,
			"user": {
				"uid": 549875,
				"name": "nosexynomoney",
				"slogan": "",
				"badge": null,
				"isAdmin": false,
				"isBanned": false,
				"color": "Blue",
				"ccfLevel": 0
			},
			"id": 59249985,
			"status": 0,
			"enableO2": false
		},
		"testCaseGroup": [
			[0, 1, 2, 3, 4]
		],
		"showStatus": true
	},
	"currentTitle": "R59249985",
}

**Comment by nosexynomoney** [comment]
哦我明白了谢谢
