### ISSUE TITLE
如何获取讨论的所有回复

### ISSUE THREAD

**Issue by swift-zym** [sjx233/luogu-api-docs#5]
`/api/discuss/replies/:id`好像只能获取第一页的回复

**Comment by sjx233** [comment]
`/api/discuss/replies/:id` 是远古 API 了，现在除了解析 HTML 以外没有什么好办法（发帖问过，被删了）

**Comment by swift-zym** [comment]
> `/api/discuss/replies/:id` 是远古 API 了，现在除了解析 HTML 以外好像没有什么好办法（发帖问过，被删了）

所以发送讨论是不是也没有api QwQ
